### ISSUE TITLE
Automate building and pushing images to Dockerhub

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend-docker#3]
@danpat want to see if we can pull this off?

**Comment by danpat** [comment]
This should be trivial if we move the `Dockerfile` into the `osrm-backend` repo, but if we don't do that, then we'd need to set up some kind of complicated sequence of triggers.

I feel ok about moving it, I think this repo had proven that it's valuable.

**Comment by daniel-j-h** [comment]
cc @TheMarex - just came across this, because we talked about moving the Docker scripts into osrm-backend. If we could automatically build and push Docker images for, say, every `tag x {release,debug,sanitized}` we do, this would be great!

**Comment by TheMarex** [comment]
I would like to see this so we could for example use it to power the demo server and use it as base for internal experimental containers.

I did some experiments with node-pre-gyp and continuously publishing binaries and there are only hacky solutions in that setup really.

**Comment by daniel-j-h** [comment]
Done in osrm-backend repo.

Closing here.
